package klientas;


import Grafika.SpalvuNustatymas;
import Labirinto_dalys.Kryptys;
import Labirinto_dalys.Labirintas;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Eimantas
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    Labirintas l;
    Klientas kl;
    ArrayList<String> klientu_nikai;
    public GUI(Klientas sis) {
        initComponents();
        Chatas.setEditable(false);// KAD NEGALETU PATS RASTI  i textarea
        klientu_nikai= new ArrayList<>();
        kl=sis;
        piesinys1.grabFocus();// be jo neveikia klavisu paspaudimas

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piesinys1 = new Grafika.Piesinys();
        jScrollPane1 = new javax.swing.JScrollPane();
        Chatas = new javax.swing.JTextArea();
        Rasymas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        KlientuSarasas = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        Redagavimas = new javax.swing.JMenu();
        SpalvuKeitimas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Labirintas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        piesinys1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                piesinys1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout piesinys1Layout = new javax.swing.GroupLayout(piesinys1);
        piesinys1.setLayout(piesinys1Layout);
        piesinys1Layout.setHorizontalGroup(
            piesinys1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        piesinys1Layout.setVerticalGroup(
            piesinys1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        Chatas.setColumns(20);
        Chatas.setRows(5);
        jScrollPane1.setViewportView(Chatas);

        Rasymas.setToolTipText("");
        Rasymas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RasymasKeyReleased(evt);
            }
        });

        jScrollPane2.setViewportView(KlientuSarasas);

        Redagavimas.setText("Redagavimas");

        SpalvuKeitimas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        SpalvuKeitimas.setText("Keisti spalvas");
        SpalvuKeitimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpalvuKeitimasActionPerformed(evt);
            }
        });
        Redagavimas.add(SpalvuKeitimas);

        jMenuBar1.add(Redagavimas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addComponent(Rasymas)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(piesinys1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(piesinys1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rasymas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void  setLabirintas (int auk, int plo){
        l = new Labirintas (auk,plo);
        piesinys1.setL(l);
        this.repaint();
    }
 
    
    private void piesinys1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_piesinys1KeyReleased
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case 38:
                l.getTaskai().get(0).eik(Kryptys.VIRSUS);
                kl.siustiZinute("eik:"+0);
                break;
            case 39:
                l.getTaskai().get(0).eik(Kryptys.DESINE);
                kl.siustiZinute("eik:"+1);
                break;
            case 40:
                l.getTaskai().get(0).eik(Kryptys.APACIA);
                kl.siustiZinute("eik:"+2);
                break;
            case 37:
                l.getTaskai().get(0).eik(Kryptys.KAIRE);
                kl.siustiZinute("eik:"+3);
                break;
        }
        /////////////////////////////////////       
        this.repaint();
    }//GEN-LAST:event_piesinys1KeyReleased

    private void SpalvuKeitimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpalvuKeitimasActionPerformed
        // TODO add your handling code here:
        SpalvuNustatymas spal= new SpalvuNustatymas(this, true);
        spal.setVisible(true);
        piesinys1.s1=spal.sp1;
        piesinys1.s2=spal.sp2;
        piesinys1.s3=spal.sp3;
        this.repaint();
    }//GEN-LAST:event_SpalvuKeitimasActionPerformed
/**/
    private void RasymasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RasymasKeyReleased
        if (evt.getKeyCode()==10 && kl!=null){
            String txt=Rasymas.getText();
            Rasymas.setText("");
            try{
            if (KlientuSarasas.getSelectedValue().equals("Visi")){
            kl.siustiZinute("v:"+txt);
            }else{
                kl.siustiZinute("pm:"+KlientuSarasas.getSelectedValue()+":"+txt);
            }
            }
            catch (Exception ex){
               kl.siustiZinute("v:"+txt);}
            isvestiAtsaka(txt);
            piesinys1.grabFocus();
        }
    }//GEN-LAST:event_RasymasKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     if (kl!=null){
            try{
                kl.siustiZinute("Bye.");
                kl.uzdarytiSrautus();
            }
            catch(Exception e){  
            }
        }
    }//GEN-LAST:event_formWindowClosing

    public void isvestiAtsaka(String txt){
        Chatas.append(txt+"\n");
        Chatas.setCaretPosition(Chatas.getDocument().getLength());// textarea rodytu i apacia
    }
    public void pridetiKlienta(String n){
        klientu_nikai.add(n);
        KlientuSarasas.setModel(new javax.swing.AbstractListModel(){
            String[] strings =klientu_nikai.toArray(new String[klientu_nikai.size()]);
            @Override
            public int getSize() {return strings.length;}
            @Override
            public Object getElementAt (int i) {return strings[i];}
        });
    }
    
    public void pasalintiKlienta(String n){
        klientu_nikai.remove(n);
        KlientuSarasas.setModel(new javax.swing.AbstractListModel() {
            String[] strings =klientu_nikai.toArray(new String[klientu_nikai.size()]);
            @Override
            public int getSize() {
              return strings.length;
            }
            @Override
            public Object getElementAt(int i) {
               return strings[i];
            }
        });
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Chatas;
    private javax.swing.JList<String> KlientuSarasas;
    private javax.swing.JTextField Rasymas;
    private javax.swing.JMenu Redagavimas;
    private javax.swing.JMenuItem SpalvuKeitimas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private Grafika.Piesinys piesinys1;
    // End of variables declaration//GEN-END:variables
}
